"""Regenerate the bundled atomic overview (optional developer tool).

Run: python3 scripts/build-dna-helix.py (requires NumPy).
Source: https://files.rcsb.org/download/1BNA.pdb, CC0 coordinate data.
The ten-pair block is extended using a least-squares screw transform fitted
from the two overlapping terminal pairs. This is an illustrative extension,
not an experimentally determined 30-pair structure. Runtime needs only JS.
"""
import numpy as np
from pathlib import Path
import json
root = Path(__file__).resolve().parents[1]
residues={}
for line in (root / 'scripts/data/dna-1bna.pdb').read_text().splitlines():
    if line.startswith('ATOM'):
        key=(line[21],int(line[22:26]))
        residues.setdefault(key,{})[line[12:16].strip()] = (line[76:78].strip(),np.array([float(line[30:38]),float(line[38:46]),float(line[46:54])]))
# Fit the ten-base-pair screw operation to the two overlapping terminal pairs.
source=[]; target=[]
for old,new in [(('A',1),('A',11)),(('A',2),('A',12)),(('B',24),('B',14)),(('B',23),('B',13))]:
    for name in sorted(residues[old].keys() & residues[new].keys()):
        source.append(residues[old][name][1]);target.append(residues[new][name][1])
a=np.array(source);b=np.array(target); ac=a.mean(0);bc=b.mean(0)
u,_,vt=np.linalg.svd((a-ac).T@(b-bc));r=vt.T@u.T
if np.linalg.det(r)<0: vt[-1]*=-1;r=vt.T@u.T
t=bc-r@ac
# Restore the terminal phosphate and its bridging oxygen from the overlap.
# The measured free 5' oxygen points away from the continuous backbone.
for name in ['P', 'OP1', 'OP2', "O5'"]:
    element,p=residues[('A',11)][name];residues[('A',1)][name]=(element,r.T@(p-t))
# A 30-bp idealized extension, using overlapping copies of the measured structure.
atoms=[]; meta=[]; bonds=[]; index={}
for block in range(3):
    for i in range(10):
        for side,key in enumerate([('A',i+1),('B',24-i)]):
            for name,(element,position) in residues[key].items():
                p=position.copy()
                for _ in range(block):p=r@p+t
                index[(block*10+i,side,name)]=len(atoms)
                atoms.append(p);meta.append([element,block*10+i,side,name])
# Covalent bonds within residues; phosphodiester links follow each chain's direction.
for i,(element,pair,side,name) in enumerate(meta):
    for j in range(i+1,len(atoms)):
        e2,p2,s2,n2=meta[j]
        if pair==p2 and side==s2:
            distance=np.linalg.norm(atoms[i]-atoms[j])
            if .9<distance<(1.95 if 'P' in [element,e2] else 1.85):bonds.append([i,j])
    next_pair=pair+(1 if side==0 else -1)
    if name=="O3'" and (next_pair,side,'P') in index:
        bonds.append([i,index[(next_pair,side,'P')]])
# Confirm that every atom belongs to one of the two continuous DNA strands.
neighbors = [set() for _ in atoms]
for first, second in bonds:
    neighbors[first].add(second)
    neighbors[second].add(first)
    assert 1 < np.linalg.norm(atoms[first] - atoms[second]) < 2.5
unseen = set(range(len(atoms)))
components = []
while unseen:
    pending = [unseen.pop()]
    count = 0
    while pending:
        current = pending.pop()
        count += 1
        new = neighbors[current] & unseen
        unseen -= new
        pending.extend(new)
    components.append(count)
assert len(components) == 2, f"Disconnected backbone: {components}"
print('Connected strand atom counts:', components)
# Principal axis upright, preserving handedness. A slight tilt exposes base stacking.
p=np.array(atoms);p-=p.mean(0)
_,_,axes=np.linalg.svd(p,full_matrices=False)
vertical=axes[0]
if np.dot(vertical,t)<0:vertical=-vertical
horizontal=np.cross(vertical,[0,0,1]);horizontal/=np.linalg.norm(horizontal)
depth=np.cross(horizontal,vertical)
coords=np.stack([p@horizontal,p@vertical,p@depth],axis=1)
output={'source':'https://www.rcsb.org/structure/1BNA','basePairs':30,'atoms':[[m[0],*np.round(c,3).tolist()] for m,c in zip(meta,coords)],'bonds':bonds}
(root / 'src/js/animations/dna-helix-data.js').write_text('// Idealized 30-bp extension of RCSB PDB 1BNA (CC0 atomic coordinates).\n// Generated by scripts/build-dna-helix.py; coordinates in angstroms. No solvent or hydrogens.\nwindow.DNA_HELIX_DATA = '+json.dumps(output,separators=(',',':'))+';\n')
print('atoms',len(atoms),'bonds',len(bonds),'range',np.ptp(coords,axis=0))
print('overlap RMSD',np.sqrt(np.mean(np.sum(((a@r.T+t)-b)**2,axis=1))))
